# 功能基础配置文件
# yml 文件语法请参考 http://www.ruanyifeng.com/blog/2016/07/yaml.html

# 构建模式
# 默认 isomorphic   
# ssr（服务端渲染） spa（单页应用） isomorphic（同构应用）
mode: "isomorphic"
# 客户端端口 （即 webpack-dev-server 运行端口）
clientSidePort: 3004
# 服务端端口 （即 node server 运行端口）
serverSidePort: 3003
